"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.newSearchChangeView = exports.saveUnlinkedHotelStatistics = exports.SaveTourOrderPhone = exports.GetMyCity = exports.GetCitiesList = exports.UserSignIn = exports.GetTourOperator = exports.GetTourOperators = exports.GetHotelsHotel = exports.GetHotels = exports.SaveRequestOrder = exports.GetResortsResort = exports.GetResorts = exports.GetCountriesList = exports.BaseModuleTourmometrApiService = void 0;
var tslib_1 = require("tslib");
tslib_1.__exportStar(require("./BaseApiService"), exports);
tslib_1.__exportStar(require("./Tour"), exports);
tslib_1.__exportStar(require("./OilTax"), exports);
tslib_1.__exportStar(require("./types"), exports);
var BaseModuleTourmometrApiService_1 = require("./ModuleApiServices/Tourmometr.svc/BaseModuleTourmometrApiService");
Object.defineProperty(exports, "BaseModuleTourmometrApiService", { enumerable: true, get: function () { return BaseModuleTourmometrApiService_1.BaseModuleTourmometrApiService; } });
var GetCountriesList_1 = require("./ModuleApiServices/Tourmometr.svc/GetCountriesList/GetCountriesList");
Object.defineProperty(exports, "GetCountriesList", { enumerable: true, get: function () { return GetCountriesList_1.GetCountriesList; } });
tslib_1.__exportStar(require("./ClaimApiServices/Main.svc/UpdateClaim/UpdateClaim"), exports);
tslib_1.__exportStar(require("./ClaimApiServices/Main.svc/GetClaimInfo/GetClaimInfo"), exports);
tslib_1.__exportStar(require("./ClaimApiServices/Main.svc/GetSettings/GetSettings"), exports);
tslib_1.__exportStar(require("./ClaimApiServices/Main.svc/GetSettings/PrepaymentSchema"), exports);
tslib_1.__exportStar(require("./ClaimApiServices/Main.svc/CreateClaim/index"), exports);
tslib_1.__exportStar(require("./ClaimApiServices/Main.svc/CreateClaim/Request"), exports);
tslib_1.__exportStar(require("./ClaimApiServices/Main.svc/CreateClaim/Response"), exports);
tslib_1.__exportStar(require("./ClaimApiServices/Main.svc/CreateClaimEx/index"), exports);
tslib_1.__exportStar(require("./ClaimApiServices/Main.svc/CreateClaimEx/Response"), exports);
tslib_1.__exportStar(require("./ClaimApiServices/Main.svc/GetPriceByScheme/GetPriceByScheme"), exports);
tslib_1.__exportStar(require("./ClaimApiServices/Main.svc/GetPriceByScheme/Request"), exports);
tslib_1.__exportStar(require("./ClaimApiServices/Main.svc/GetPriceByScheme/Response"), exports);
tslib_1.__exportStar(require("./AdsApiServices/Advertisements.svc/GetBanners/GetBanners"), exports);
tslib_1.__exportStar(require("./AdsApiServices/Advertisements.svc/GetBanners/GetBannersResponse"), exports);
tslib_1.__exportStar(require("./AdsApiServices/Advertisements.svc/GetBanners/Banner"), exports);
tslib_1.__exportStar(require("./AdsApiServices/Advertisements.svc/GetBanners/BannerImage"), exports);
tslib_1.__exportStar(require("./AdsApiServices/Advertisements.svc/GetBanners/BannerTypes"), exports);
tslib_1.__exportStar(require("./AdsApiServices/Advertisements.svc/GetNextAdsJson/GetNextAdsJsonResponse"), exports);
tslib_1.__exportStar(require("./AdsApiServices/Advertisements.svc/GetNextAdsJson/GetNextAdsJson"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetTours/GetTours"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetTours/Tour"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetTours/GetToursAsync"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetTours/GetToursRequest"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetTours/GetToursResponse"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetTours/OilTax"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetTours/VisaFee"), exports);
var GetCities_1 = require("./ModuleApiServices/Main.svc/GetCities/GetCities");
Object.defineProperty(exports, "GetResorts", { enumerable: true, get: function () { return GetCities_1.GetCities; } });
var GetCitiesResponse_1 = require("./ModuleApiServices/Main.svc/GetCities/GetCitiesResponse");
Object.defineProperty(exports, "GetResortsResort", { enumerable: true, get: function () { return GetCitiesResponse_1.Resort; } });
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/SaveTourOrder/SaveTourOrder"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/SaveTourOrder/SaveTourOrderRequest"), exports);
var SaveRequestOrder_1 = require("./ModuleApiServices/Main.svc/SaveRequestOrder/SaveRequestOrder");
Object.defineProperty(exports, "SaveRequestOrder", { enumerable: true, get: function () { return SaveRequestOrder_1.SaveRequestOrder; } });
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetCountries/GetCountries"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetDepartCities/GetDepartCities"), exports);
var GetHotels_1 = require("./ModuleApiServices/Main.svc/GetHotels/GetHotels");
Object.defineProperty(exports, "GetHotels", { enumerable: true, get: function () { return GetHotels_1.GetHotels; } });
var GetHotelsResponse_1 = require("./ModuleApiServices/Main.svc/GetHotels/GetHotelsResponse");
Object.defineProperty(exports, "GetHotelsHotel", { enumerable: true, get: function () { return GetHotelsResponse_1.Hotel; } });
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetHotelInfo/GetHotelInfo"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetHotelInfo/GetHotelInfoResponse"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetHotelStars/GetHotelStars"), exports);
var GetTourOperators_1 = require("./ModuleApiServices/Main.svc/GetTourOperators/GetTourOperators");
Object.defineProperty(exports, "GetTourOperators", { enumerable: true, get: function () { return GetTourOperators_1.GetTourOperators; } });
var GetTourOperatorsResponse_1 = require("./ModuleApiServices/Main.svc/GetTourOperators/GetTourOperatorsResponse");
Object.defineProperty(exports, "GetTourOperator", { enumerable: true, get: function () { return GetTourOperatorsResponse_1.Operator; } });
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetTourDates/GetTourDates"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetTemplates/GetTemplates"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetTemplates/Template"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetShowcaseReview/GetShowcaseReview"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetShowcaseReview/Showcase"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetMeals/GetMeals"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetLoadState/GetLoadState"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetLoadState/GetLoadStateResponse"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/ActualizePrice/ActualizePrice"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/ActualizePrice/ActualizePriceRequest"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/ActualizePrice/ActualizePriceResponse"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/ActualizePrice/Resources"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/ActualizePrice/OilTaxes"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/ActualizePrice/VisaFees"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetActualizationResult/GetActualizationResult"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetActualizationResult/GetActualizationResultAsync"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetActualizationResult/Request"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/QueueActualization/QueueActualization"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/QueueActualization/Request"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/QueueActualization/Response"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetTourCardInfo"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetOffices/GetOffices"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetOffices/GetOfficesResponse"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Main.svc/GetJuridicalData/GetJuridicalData"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/BaseModuleApiService"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Comments.svc/GetComments/GetComments"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Comments.svc/GetComments/GetCommentsRequest"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Comments.svc/GetComments/GetCommentsResponse"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Comments.svc/AddLargeComment/AddLargeComment"), exports);
tslib_1.__exportStar(require("./ModuleApiServices/Comments.svc/AddLargeComment/AddLargeCommentRequest"), exports);
tslib_1.__exportStar(require("./ModuleConfigsApiService/get-config"), exports);
tslib_1.__exportStar(require("./ModuleConfigsApiService/types"), exports);
tslib_1.__exportStar(require("./UISletatApiServices/Morpher.svc/GetCases/GetCases"), exports);
tslib_1.__exportStar(require("./UISletatApiServices/LandingTours.svc/BaseUISletatLandingToursApiService"), exports);
tslib_1.__exportStar(require("./UISletatApiServices/LandingTours.svc/GetTownFromByIp/GetTownFromByIp"), exports);
tslib_1.__exportStar(require("./UISletatApiServices/API/BaseUISletatApiService"), exports);
tslib_1.__exportStar(require("./UISletatApiServices/API/CountryHotels/CountryHotels"), exports);
tslib_1.__exportStar(require("./UISletatApiServices/API/CountryHotels/CountryHotelsQueryBuilder"), exports);
tslib_1.__exportStar(require("./UISletatApiServices/API/GetHotelOnMapImage/GetHotelOnMapImage"), exports);
tslib_1.__exportStar(require("./UISletatApiServices/API/Mail/About/MailAboutService"), exports);
tslib_1.__exportStar(require("./SletatServices/BaseSletatService"), exports);
tslib_1.__exportStar(require("./SletatServices/Services/BaseSletatServicesService"), exports);
tslib_1.__exportStar(require("./SletatServices/Services/GetTourOperatorsWithOnlineBilling/GetTourOperatorsWithOnlineBilling"), exports);
tslib_1.__exportStar(require("./SletatServices/Services/GetHotelMapImage/GetHotelMapImage"), exports);
tslib_1.__exportStar(require("./SletatServices/Services/SendConfirmEmail/SendConfirmEmail"), exports);
tslib_1.__exportStar(require("./SletatServices/Services/Basket/Basket"), exports);
tslib_1.__exportStar(require("./SletatServices/Services/Promo/Promo"), exports);
tslib_1.__exportStar(require("./SletatServices/Authentification"), exports);
tslib_1.__exportStar(require("./SletatServices/API/BaseSletatApiService"), exports);
tslib_1.__exportStar(require("./SletatServices/API/TourComplaint/TourComplaint"), exports);
var UserSignIn_1 = require("./SletatServices/API/user/SignIn/UserSignIn");
Object.defineProperty(exports, "UserSignIn", { enumerable: true, get: function () { return UserSignIn_1.UserSignIn; } });
tslib_1.__exportStar(require("./SletatServices/API/Hotels/ReportAnError"), exports);
tslib_1.__exportStar(require("./SletatServices/API/Hotels/AddHotelComment"), exports);
tslib_1.__exportStar(require("./URLShortener/URLShortener"), exports);
var GetCities_2 = require("./UISletatApiServices/WhereToBuy/GetCities/GetCities");
Object.defineProperty(exports, "GetCitiesList", { enumerable: true, get: function () { return GetCities_2.GetCitiesList; } });
var GetMyCity_1 = require("./UISletatApiServices/WhereToBuy/GetMyCity/GetMyCity");
Object.defineProperty(exports, "GetMyCity", { enumerable: true, get: function () { return GetMyCity_1.GetMyCity; } });
tslib_1.__exportStar(require("./UISletatApiServices/WhereToBuy/GetOffices/GetOffices"), exports);
var SaveTourOrder_1 = require("./SletatServices/Tour.aspx/SaveTourOrder/SaveTourOrder");
Object.defineProperty(exports, "SaveTourOrderPhone", { enumerable: true, get: function () { return SaveTourOrder_1.SaveTourOrderPhone; } });
var SaveUnlinkedHotelStatistics_1 = require("./SletatServices/Tour.aspx/SaveUnlinkedHotelStatistics/SaveUnlinkedHotelStatistics");
Object.defineProperty(exports, "saveUnlinkedHotelStatistics", { enumerable: true, get: function () { return SaveUnlinkedHotelStatistics_1.saveUnlinkedHotelStatistics; } });
var NewSearch_1 = require("./SletatServices/Services/NewSearch/NewSearch");
Object.defineProperty(exports, "newSearchChangeView", { enumerable: true, get: function () { return NewSearch_1.newSearchChangeView; } });
